server:
  shutdown: graceful
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false

application:
  version: /v1
  prefix: /api
  exclude-prefix-path: springdoc

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

logging:
  level:
    root: ${lrc.management.api.logging.level.root:INFO}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${lrc.management.api.logging.level.mongo:INFO}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    io:
      spring:
        cloud: INFO

---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: ${lrc.mongo.host:localhost}
      port: ${lrc.mongo.port:27017}
      database: ${lrc.mongo.database:test}

---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: default
  data:
    mongodb:
      host: ${lrc.mongo.host:localhost}
      port: ${lrc.mongo.port:27017}
      database: ${lrc.mongo.database:test}

---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
