apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrc-mng-api
  namespace: NAMESPACE
  labels:
    app: lrc-mng-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lrc-mng-api
  strategy: {}
  template:
    metadata:
      labels:
        app: lrc-mng-api
    spec:
      containers:
        - name: lrc-mng-api
          image: AWS_ECR_URI
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: varlog
              mountPath: /app/logs
        - name: fluentd-agent
          image: k8s.gcr.io/fluentd-gcp:1.30
          env:
            - name: FLUENTD_ARGS
              value: -c /etc/fluentd-config/fluentd.conf -c /etc/fluentd-config/kubernetes.conf
            volumeMounts:
              - name: varlog
                mountPath: /app/logs
              - name: config-volume
                mountPath: /etc/fluentd-config
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config